version: "3.3"
services:
  api:
    build: ./api
    ports:
      - "8083:8083"
  frontend:
    build: ./public
    volumes: 
      - './public:/frontend'
      - '/frontend/node_modules'
    ports:
      - "80:80"

  db:
    image: postgres:13.3-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080