version: "3.3"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
  frontend:
    build: ./public
    ports:
      - "80:80"

  db:
    image: postgres:13.3-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081